apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: orders-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: orders-api  
    spec:     # pod spec                  
      containers: 
      - name: orders-api 
        image: gcr.io/mariadb-technical-marketing/orders-api-image:v1 # image we pushed
        ports:
        - containerPort: 80