apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: orders-ui-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: orders-ui  
    spec:     # pod spec                  
      containers: 
      - name: orders-ui 
        image: gcr.io/mariadb-technical-marketing/orders-ui-image:v3 # image we pushed
        ports:
        - containerPort: 80